fix(changelog): update license, commit links in changelog and metrics
DevIntent/verdaccio-prometheus-middleware pull request #1
Opened 2023-10-09 10:29 UTC by jzolnowski

- fix links to commits in changelog
- remove unnecessary metrics
- fix `No files matching the pattern "'**/*.{js,ts}'" were found` when
  run lint (for Windows)

2023-10-11 16:03 UTC, Splaktar requested changes

2023-10-11 16:03 UTC, Splaktar commented on CHANGELOG.md
> +- **metrics:** collect http request metrics and package download metrics ([7f26b37](https://github.com/DevIntent/verdaccio-prometheus-middleware/commit/7f26b37ee90f056ee07bfa4f760a2a084cb6d9c5)), clo
https://github.com/DevIntent/verdaccio-prometheus-middleware/issues/9 isn't going to work since the issues don't copy over to the new repo. This should continue to point to the old repo for the issue.

2023-10-11 16:03 UTC, Splaktar commented on CHANGELOG.md
> +- **metrics:** collect http request metrics and package download metrics ([7f26b37](https://github.com/DevIntent/verdaccio-prometheus-middleware/commit/7f26b37ee90f056ee07bfa4f760a2a084cb6d9c5)), clo
Same issue with the other changes.

2023-10-18 15:45 UTC, jzolnowski commented on CHANGELOG.md
> +- **metrics:** collect http request metrics and package download metrics ([7f26b37](https://github.com/DevIntent/verdaccio-prometheus-middleware/commit/7f26b37ee90f056ee07bfa4f760a2a084cb6d9c5)), clo
@Splaktar I don't have an access to Issues on this repo 😄

2023-10-18 15:55 UTC, jzolnowski commented on CHANGELOG.md
> +- **metrics:** collect http request metrics and package download metrics ([7f26b37](https://github.com/DevIntent/verdaccio-prometheus-middleware/commit/7f26b37ee90f056ee07bfa4f760a2a084cb6d9c5)), clo
Fixed

2023-10-18 16:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/DevIntent/verdaccio-prometheus-middleware?pullRequest=1) <br/>All committers have signed the CLA.

2023-10-18 16:29 UTC, jzolnowski commented
Not sure why unit tests failed. I did fix that issue [here](https://github.com/DevIntent/verdaccio-prometheus-middleware/blob/56426f86681e38f69bc3bc57fb973dbbc324252d/tests/pluginMetricsDefault.spec.ts)

2023-10-18 18:59 UTC, Splaktar commented
@jzolnowski please sign the CLA. I'm not sure what's going on with the tests.

2023-10-18 19:25 UTC, Splaktar requested changes
Please break up the changes into 2 commits and update the changelog to the following
```
docs(changelog): fix links to commits in changelog
```
```
test(pluginMetricsDefault): remove unnecessary metrics

- fix `No files matching the pattern "'**/*.{js,ts}'" were found` when run lint
```
Is this only seen on Windows? If so, we should state that the fix is for Windows.

2023-11-01 17:01 UTC, jzolnowski commented
> Is this only seen on Windows? If so, we should state that the fix is for Windows.

Correct, but it's also consistent with other projects e.g. [verdaccio-google-cloud-storage](https://github.com/DevIntent/verdaccio-google-cloud-storage/blob/master/package.json#L68),  or [devintent](https://github.com/DevIntent/devintent/blob/master/package.json#L29)

2023-11-01 17:38 UTC, Splaktar approved these changes

2023-11-01 17:38 UTC, Splaktar commented on LICENSE.md
> +Copyright (c) 2023 DevIntent
This doesn't render properly in markdown. This minor change will fix it.
```suggestion
- Copyright (c) 2022 XLTS.dev
- Copyright (c) 2023 DevIntent
```

2023-11-03 00:40 UTC, Splaktar commented
From https://github.com/siimon/prom-client/blob/master/README.md#default-metrics:

> NOTE: Some of the metrics, concerning File Descriptors and Memory, are only available on Linux.

So CircleCI on Linux will have a different set of metrics compared to a local machine (macOS). @jzolnowski can you please update this test to run differently if on CircleCI?

2023-11-03 00:41 UTC, Splaktar requested changes
Need to check different metrics if running in CircleCI.

2023-11-03 18:03 UTC, jzolnowski commented
> So CircleCI on Linux will have a different set of metrics compared to a local machine (macOS). @jzolnowski can you please update this test to run differently if on CircleCI?

I can look into it, but at this point I don't know the configuration of tests on this repository

2023-11-07 10:33 UTC, jzolnowski commented
@Splaktar unit tests fixed 🎉

2023-11-07 16:24 UTC, Splaktar requested changes

2023-11-07 16:24 UTC, Splaktar commented on tests/pluginMetricsDefault.spec.ts
> +      const baseMetrix = [
```suggestion
      const baseMetrics = [
```

2023-11-07 16:24 UTC, Splaktar commented on tests/pluginMetricsDefault.spec.ts
> +      const linuxMetrix = [
```suggestion
      const linuxMetrics = [
```

2023-11-07 16:24 UTC, Splaktar commented on tests/pluginMetricsDefault.spec.ts
> +      expect(metrics.map(({ name }) => name).sort()).toEqual(process.platform === 'linux' ? linuxMetrix : baseMetrix);
```suggestion
      expect(metrics.map(({ name }) => name).sort()).toEqual(process.platform === 'linux' ? linuxMetrics : baseMetrics);
```

2023-11-10 14:17 UTC, jzolnowski commented on tests/pluginMetricsDefault.spec.ts
> +      const baseMetrix = [
Fixed

2023-11-10 14:17 UTC, jzolnowski commented on tests/pluginMetricsDefault.spec.ts
> +      const linuxMetrix = [
Fixed

2023-11-10 14:17 UTC, jzolnowski commented on tests/pluginMetricsDefault.spec.ts
> +      expect(metrics.map(({ name }) => name).sort()).toEqual(process.platform === 'linux' ? linuxMetrix : baseMetrix);
Fixed

2023-11-10 18:23 UTC, Splaktar approved these changes

2023-11-10 18:24 UTC, merged